enhance sechub-api shell script #498
Daimler/sechub pull request #615
Opened 2021-05-07 16:09 UTC by sven-dmlr

- scheduler handling added
- project handling extended
- profiles handling added
- executor handling added
- fixed some typos

closes #498

2021-05-10 07:10 UTC, Jeeppler requested changes

2021-05-10 07:10 UTC, Jeeppler commented on sechub-developertools/scripts/sechub-api.sh
> +  curl $CURL_PARAMS -i -X DELETE -H 'Content-Type: application/json' "$SECHUB_SERVER/api/admin/config/execution/profile/$2/project/$1" | $RESULT_FILTER | $JSON_FORMATTER
Whenever you use two or more method arguments, they should be put into variables. The problem is, that functions in Shell scripts don't allow arguments in the signature. As a result, it is difficult to see the order of the variables. Please use variables properly named variables, to make the order clearly visible.

```
profile_id=$2
project_id=$1

curl $CURL_PARAMS …
```

2021-05-10 07:10 UTC, Jeeppler commented on sechub-developertools/scripts/sechub-api.sh
> +  curl $CURL_PARAMS -i -X DELETE -H 'Content-Type: application/json' "$SECHUB_SERVER/api/admin/project/$1/membership/$2" | $RESULT_FILTER | $JSON_FORMATTER
As mentioned multiple times, please use variables.

2021-05-11 07:34 UTC, sven-dmlr commented on sechub-developertools/scripts/sechub-api.sh
> +  curl $CURL_PARAMS -i -X POST -H 'Content-Type: application/json' "$SECHUB_SERVER/api/admin/config/execution/profile/$2/project/$1" | $RESULT_FILTER | $JSON_FORMATTER
There are explaining variable names already there. Please see here e.g.:
![self-explaining-variables](https://user-images.githubusercontent.com/59958584/117776056-66a78000-b23b-11eb-8868-8b8b89d8ac24.png)
So using extra variable names in the one-liner-functions as well looks for me like bloating the code with almost no gain.

Also the called URLs are almost self-explaining. See some examples:
![self-explaining-urls](https://user-images.githubusercontent.com/59958584/117776380-cc940780-b23b-11eb-9360-12983d9bd48b.png)
So I would leave the code as it is. :-)

2021-05-11 11:46 UTC, Jeeppler approved these changes

2021-05-20 07:17 UTC, merged