Accept only TLS1.2 and TLs1.3 #624
Daimler/sechub pull request #644
Opened 2021-05-27 12:31 UTC by de-jcup

Security improvement PR

- closes #624 
- closes #625

2021-06-09 10:02 UTC, Jeeppler requested changes
See comments.

2021-06-09 10:02 UTC, Jeeppler commented on sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/security/ServerEncryptionTest.java
> +        securityTestHelper = new SecurityTestHelper(TestTargetType.SECHUB_SERVER,new URL(checkAlive));
```suggestion
        securityTestHelper = new SecurityTestHelper(TestTargetType.SECHUB_SERVER, new URL(checkAlive));
```

2021-06-10 07:50 UTC, de-jcup commented on sechub-integrationtest/ciphertest.sh
> +ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g')
done

2021-06-10 07:51 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +        String cipher  =check.cipher;
done - sourcecode formatter applied

2021-06-10 07:51 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +        if (lastIndex==-1) {
done - sourcecode formatter applied

2021-06-10 07:53 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +                        fail("Not wanted mac:"+mac+" found inside verfified cipher:"+check.cipher);
done

2021-06-10 07:53 UTC, de-jcup commented on sechub-integrationtest/src/test/java/com/daimler/sechub/integrationtest/security/ServerEncryptionTest.java
> +        securityTestHelper = new SecurityTestHelper(TestTargetType.SECHUB_SERVER,new URL(checkAlive));
done - sourcecode formatter applied

2021-06-10 08:21 UTC, Jeeppler approved these changes

2021-06-10 08:21 UTC, merged