Improved DAUI ui for key values parameters, closes #646
Daimler/sechub pull request #647
Opened 2021-05-27 16:39 UTC by de-jcup

This PR 

- closes #646 
- closes #435

2021-06-02 10:02 UTC, Jeeppler requested changes
See comments.

2021-06-07 13:41 UTC, de-jcup commented on sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/PDSAdapterV1WireMockTest.java
> +        expectedJobParameters = new TreeMap<>();
The reason for this is that a tree map is always sorted. this is easier to debug. And we are talking about some simple parameters.

2021-06-09 09:47 UTC, de-jcup commented on sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/PDSWiremockTestSupport.java
> +//    public IcrementalAdditionalPrefixAPIURLSupport getApiURLSupport() {
dropped comments

2021-06-09 09:51 UTC, de-jcup commented on sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/PDSWiremockTestSupport.java
> +            for (UploadInfo info : uploads) {
At the moment we only use sourcecode.zip - but we will provide more in future - e.g. binary-arifact.obj or something.
The accepted uploads are managed by PDS server. The test support here just provides a possiblity to handle this in our tests as well - e.g. when somebody tries to upload sourcecode.zip files again and again etc. (another testscenario, but currently not implemented).

2021-06-09 09:53 UTC, de-jcup commented on sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/PDSWiremockTestSupport.java
> +        Exception e) {
done

2021-06-09 09:59 UTC, de-jcup commented on sechub-adapter-pds/src/test/java/com/daimler/sechub/adapter/pds/PDSWiremockTestSupport.java
> +                // .inScenario(chain.getScenario()).whenScenarioStateIs(chain.getStateBefore())
done

2021-06-09 10:01 UTC, de-jcup commented on sechub-developertools/src/main/java/com/daimler/sechub/developertools/admin/ui/action/adapter/ProductExecutorTemplatesDialogUI.java
> +            System.out.println("No input content found!!!");
Maybe, maybe not ;-) - but I removed it as suggested. So done.

2021-06-09 10:21 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/diagrams/diagram_concept_pds_storage_example_shared_s3_bucket.puml
> +
done

2021-06-09 10:24 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +{pds} needs - like {sechub} - the possiblity to store job data in a central way when operating
Done

2021-06-09 10:30 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +For {secHub} there were already existing (and autark) storage mechanism for S3 and for shared volumes.
Changed to
```asciidoc
{pds} does use the `sechub-storage-*` libraries which provide storage mechanism for S3 and 
for shared volumes.
```
So it becomes more clear.

2021-06-09 10:32 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +For non clustered environment "shared volumes" can also be normal local file system pathes like
done

2021-06-09 10:33 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +In the next example PDS and SecHub are using same S3 bucket as storage.
done

2021-06-09 10:40 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +  In this case the way is exactly as shown in next picture: +
done

2021-06-09 10:41 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +  - The user uploads job data for a  {secHub} job and it is stored at shared S3 bucket _(blue lines)_.
done

2021-06-09 11:36 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +  - The user uploads job data for a  {secHub} job and it is stored at shared volume _(blue lines)_.
done

2021-06-09 11:36 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +  - When PDS job is starting the  PDS server will fetch workspace files from existing {secHub} job data _(red lines)_.
done

2021-06-09 11:37 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +  - The user uploads job data for a  {secHub} job and it is stored at sechub shared volume _(blue lines)_.
done

2021-06-09 11:38 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/pds_storage_configuration.adoc
> +When using own storage for PDS servers, {secHub}  has to upload already pesisted job data _(e.g. zipped sourcecode for SAST scannings)_
done

2021-06-09 11:39 UTC, de-jcup commented on sechub-pds/src/test/java/com/daimler/sechub/pds/job/PDSWorkspaceServiceTest.java
> +        entry.setKey(key);;
done

2021-06-09 11:39 UTC, de-jcup commented on sechub-pds/src/test/java/com/daimler/sechub/pds/job/PDSWorkspaceServiceTest.java
> +        entry.setValue(value);;
done

2021-06-09 11:41 UTC, de-jcup commented on sechub-testframework/src/main/java/com/daimler/sechub/test/JSONTestUtil.java
> +        for (Iterator<Object> it = list.iterator();it.hasNext();) {
Still valid - same as in another review:

```java
           if (it.hasNext()) {
                sb.append(",\n");
            }
```
only possible on iterators....

So will keep as is.

2021-06-09 11:44 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +WARNING: This will NOT WORK! The job storage will not be found and a error will happen at job execution time.
done

2021-06-09 11:44 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds.adoc
> +WARNING: This will NOT WORK! The job storage will not be found and a error will happen at job execution time.
done

2021-06-09 12:41 UTC, Jeeppler approved these changes

2021-06-09 12:41 UTC, merged