Improved security logging #664
Daimler/sechub pull request #666
Opened 2021-06-23 07:43 UTC by de-jcup

This PR 
- closes #664

2021-06-25 20:14 UTC, Jeeppler requested changes
See comments.

2021-06-28 11:37 UTC, de-jcup commented on sechub-integrationtest/send_curl_request.sh
> +if [ -z "$1" ] ; then
done

2021-06-28 11:37 UTC, de-jcup commented on sechub-integrationtest/send_curl_request.sh
> +curl --insecure -X $2 -H "Content-Type: application/json" $1
done

2021-06-28 11:38 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +            throw new IllegalStateException("Was not able to wait for ciphertest.sh result");
yes... it was copy waste failure.

2021-06-28 11:43 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +            throw new IllegalStateException("Was not able to wait for ciphertest.sh result");
Done + additionally created static variables to define the name only one time

2021-06-28 11:48 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/SecurityTestHelper.java
> +            throw new IllegalStateException("Was not able to execut curl, exit code was:"+exitCode);
done

2021-06-28 11:50 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AssertSecurityLog.java
> +            // we use equals to have IDE compare also available in outputs
The comment was to explain why the asserEquals was used and not a simple fail when already tested. 
But I will remove the comment.

2021-06-28 11:53 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/AuthorizeValueObfuscator.java
> +        boolean atleastHalfOfThePwdWouldBeObfuscated = value.length() > showRealChars + SHOWN_REAL_CHARS_OF_PASSWORD;
As we discussed before - we will change the obfuscation behaviour and I will remove this variable at all

2021-06-28 13:27 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/AuthorizeValueObfuscator.java
> +     * After this
done

2021-06-28 13:30 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/AuthorizeValueObfuscator.java
> +            return "*****length was:" + value.length();
Change the ouptut in another way - already changed to a configurable minimum size parameter.

When called for a password obfuscation with 52 and text has a size of 52 the output will be:
"aW***length:52",
When mimum is not reached, the output will be 
***length:51
This is shorter and easier to read.

2021-06-28 13:31 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/DefaultSecurityLogService.java
> +         * convert this to a new list, otherwise slf4j becomes problems with identifying
OMG: "I become a schnitzel! :facepalm: Thanx a lot!

2021-06-28 13:32 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/DefaultSecurityLogService.java
> +         * this as list and having wrong output
done

2021-06-28 13:34 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/DefaultSecurityLogService.java
> +            getLogger().warn("Security log service was called with no log type, so call was wrong implemented! Use fallback:{}", logData.type);
done

2021-06-28 13:35 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/DefaultSecurityLogService.java
> +                    "Maximum header values ({}) reached in request from ip={} - header amoutn was {} at all! So truncate header values inside next log entry!",
done

2021-06-28 13:35 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/LogSanitizer.java
> +     *                          use <=0 when Length doesn't matter
done

2021-06-28 13:36 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/LogSanitizer.java
> +     *                          use <=0 when Length doesn't matter
done

2021-06-28 13:46 UTC, de-jcup commented on sechub-shared-kernel/src/main/java/com/daimler/sechub/sharedkernel/logging/LogSanitizer.java
> +     * @param handleLogForgery  enables log forgery handling
Even when this is not introduced inside the PR, it is a good Idea to add the mentioned links.
The sanitizer handles https://cwe.mitre.org/data/definitions/93.html
and https://cwe.mitre.org/data/definitions/117.html

We use slf4 for logging, which should IMHO already handle CWE-116 already.

I will add links for CWE 93 and CWE 117.

2021-06-28 15:49 UTC, de-jcup commented
Hm... Analyzing tests did show up that our Junit5 tests are all executed by gradle except in `sechub-integrationtest` sub module!

Must be fixed!

2021-06-29 11:18 UTC, Jeeppler approved these changes

2021-06-29 11:18 UTC, merged