Feature 643 provide pds streams per rest
Daimler/sechub pull request #802
Opened 2021-09-22 13:10 UTC by de-jcup

2021-09-27 14:29 UTC, Jeeppler requested changes
See comments.

Tested with PDS single and cluster instances.

2021-09-27 14:29 UTC, Jeeppler commented on sechub-pds/src/test/java/com/daimler/sechub/pds/job/PDSUpdateJobStreamContentServiceTest.java
> +// SPDX-License-Identifier: MIT
Please apply formatter.

2021-09-28 09:20 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/diagrams/diagram_pds_overview_stream_access.puml
> +note over pdsMember2: Just fetch final data from DB".
done

2021-09-28 12:58 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/diagrams/diagram_pds_overview_stream_access.puml
> +note over pdsMember2: Cluster member2 has no \ndirect access to the job\nwhich runs on another member!".
done

2021-09-28 13:00 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/diagrams/diagram_pds_overview_stream_access.puml
> +note over pdsAdmin, pdsMember2: Administrator wants to fetch content stream\nbut loadbalancer uses other cluster member\nwhich does not execute the process".
done

2021-09-28 13:05 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds_fetch_stream_of_running_job.adoc
> +/ operation this becomes tricky in clusted environment, because the process
done

2021-09-28 14:17 UTC, de-jcup commented on sechub-doc/src/docs/asciidoc/documents/shared/concepts/concept_pds_fetch_stream_of_running_job.adoc
> +error stream content of a running job, the information shall be gathered lazily.
done

2021-09-28 14:19 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/AssertSecHubReport.java
> +             * in this case we log out the complete JSON content - interesting for debugging
done

2021-09-28 14:22 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/ExecutionConstants.java
> +     * executors do need their information by ENVIRONEMNT variables. This is a fix
done

2021-09-28 14:24 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/api/TestAPI.java
> +     * Waits for sechub job being running
done

2021-09-28 14:25 UTC, de-jcup commented on sechub-integrationtest/src/main/java/com/daimler/sechub/integrationtest/scenario2/Scenario2.java
>  import com.daimler.sechub.integrationtest.api.TestProject;
done

2021-09-28 14:55 UTC, Jeeppler approved these changes

2021-09-30 07:05 UTC, merged