typos fixed
Daimler/sechub pull request #935
Opened 2022-01-08 09:43 UTC by Vivek-Prajapatii

@Jeeppler typos fixed as you asked to do, if there is any other please let me know.

2022-01-10 08:27 UTC, Jeeppler requested changes
Good job. However, I found one issue. Please improve this.

2022-01-10 08:27 UTC, Jeeppler commented on sechub-commons-pds/src/main/java/com/daimler/sechub/commons/pds/PDSConfigDataKeyProvider.java
> +            "This Contains the SecHub configuration as JSON object (but reduced to current scan type, so e.g. a web scan will have no code scan configuration data available")
```suggestion
            "This contains the SecHub configuration as JSON object (but reduced to current scan type, so e.g. a web scan will have no code scan configuration data available")
```

2022-01-10 08:44 UTC, Jeeppler commented
@de-jcup and @sven-dmlr can you please explain what the extra requirements for a FOSS contribution at Mercedes-Benz are.

2022-01-10 09:03 UTC, Jeeppler commented
@Vivek-Prajapatii to be able to accept your pull request we ask you to sign the Contributor License Agreement (CLA). Our Wiki page explains how to sign the Contributor License Agreement (CLA): https://github.com/Daimler/sechub/wiki/Collaboration.

In case you have questions regarding the CLA or the process, feel free to ask us.

2022-01-10 15:52 UTC, Jeeppler approved these changes
Good work.

2022-01-10 15:52 UTC, Jeeppler commented
@de-jcup can you add your review as well?

2022-01-14 08:18 UTC, de-jcup requested changes
@Vivek-Prajapatii : Thank you for your contribution. Unfortunately I still have not your signed CLA . 

CLA signing is pretty simple - see https://github.com/Daimler/sechub/wiki/Collaboration#in-a-nutshell 

Please give me feedback when you have signed and mailed the CLA. After this I will approve and merge your PR.

2022-01-14 09:01 UTC, Vivek-Prajapatii commented
Yes sure I'll sign it asap.

2022-01-15 08:19 UTC, Vivek-Prajapatii commented
done with t he CLA @de-jcup

2022-01-18 07:59 UTC, merged

2022-01-18 08:33 UTC, de-jcup commented
@Vivek-Prajapatii - thanks for contribution. 

Just a remark: You did not provide the issue number inside your commit messages, so it was not easy find the corresponding issue, assign the milestone and close it. But this was also a lack of information inside our wiki, so I just added these point there at https://github.com/Daimler/sechub/wiki/Collaboration#commit-messages. Please read and apply in future contributions.

2022-01-19 08:39 UTC, Jeeppler commented
@Vivek-Prajapatii thank you for your contribution. We appreciate, that you took the effort to finish this pull-request by submitting the code and signing the Contributor License Agreement (CLA).